"""empty message

Revision ID: 1784db63bd7f
Revises: a33ff6ab47a6
Create Date: 2020-06-01 00:48:28.636683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1784db63bd7f'
down_revision = 'a33ff6ab47a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genre_venue_id_fkey', 'venue_genre', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genre', 'venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genre', type_='foreignkey')
    op.create_foreign_key('venue_genre_venue_id_fkey', 'venue_genre', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
