"""empty message

Revision ID: 1d018611247e
Revises: 1cfa7ea86f87
Create Date: 2020-05-31 01:03:10.257554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d018611247e'
down_revision = '1cfa7ea86f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    op.create_unique_constraint(None, 'state', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
